name: CI Azure App Service Deployment

on:
 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

    workflow_dispatch:

jobs:
 
  build:
    
    runs-on: ubuntu-latest

   
    steps:
      
      - uses: actions/checkout@v2

      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      
      - name: Install dependencies
        run: npm install

      #- name: Run test
      #  run: npm test

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
  # Deploy To Heroku
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
#      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
